#!/bin/sh

set -e;

echo "Running pre-commit hook: Generated combined BaselineFluentHttpExtensions.cs file."
cd Baseline.FluentHttpExtensions.FileCombiner/ && \
    dotnet run && \
    cd ../../ && \
    git add BaselineFluentHttpExtensions.cs;
echo "Running pre-commit hook: Finished combining BaselineFluentHttpExtensions.cs file."
