#!/bin/sh

set -e;

echo "Running pre-commit hook: Generating combined BaselineFluentHttpExtensions.cs file."
cd src/Baseline.FluentHttpExtensions.FileCombiner/ && \
    dotnet run && \
    cd ../../ && \
    git add BaselineFluentHttpExtensions.cs && \
    cp BaselineFluentHttpExtensions.cs src/Baseline.FluentHttpExtensions.CombinedFileTests/ && \
    git add src/Baseline.FluentHttpExtensions.CombinedFileTests/BaselineFluentHttpExtensions.cs;
echo "Running pre-commit hook: Finished combining BaselineFluentHttpExtensions.cs file."
